// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkbmrxljpethwnweoydx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYm1yeGxqcGV0aHdud2VveWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Mzg3OTYsImV4cCI6MjA1ODIxNDc5Nn0.Bi00Aiwhty1xcRxB31ahePaLgv-JZlwOdI5bvrsRBbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);